from bs4 import BeautifulSoup
import json

html_input = """

<tbody><tr id="issuerow3152607" rel="3152607" data-issuekey="WMFE-1357" class="issuerow focused"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1357" href="/browse/WMFE-1357" aria-describedby="aui-tooltip" tabindex="-1"></a>     <a class="issue-link" data-issue-key="WMFE-1357" href="/browse/WMFE-1357">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1357" href="/browse/WMFE-1357">WMFE-1357</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1357" href="/browse/WMFE-1357">v25.5 [동적그룹] not 'A' 조건 추가 &gt; A 조건 만족하는 구성원이 타도메인 겸직 있을 경우 그룹 멤버로 추가됨</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13263" id="assignee_NB13263" href="/secure/ViewProfile.jspa?name=NB13263">진조환[Directory Dev]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13263" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT11572" id="reporter_NT11572" href="/secure/ViewProfile.jspa?name=NT11572">김문지[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT11572" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span aria-describedby="aui-tooltip"><time datetime="2025-03-28T19:11:23+0900">2025-03-28</time></span> </td><td class="updated"> <span title="2025-05-08 16:53"><time datetime="2025-05-08T16:53:53+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"><span class="pull-requests"><a class="fusion-widget" data-dev-type="pullrequest" data-issue-id="3152607" data-issue-key="WMFE-1357" data-dev-summary="{&quot;cachedValue&quot;:{&quot;errors&quot;:[],&quot;configErrors&quot;:[],&quot;summary&quot;:{&quot;pullrequest&quot;:{&quot;overall&quot;:{&quot;count&quot;:2,&quot;lastUpdated&quot;:&quot;2025-04-30T14:58:57.000+0900&quot;,&quot;stateCount&quot;:2,&quot;state&quot;:&quot;MERGED&quot;,&quot;details&quot;:{&quot;openCount&quot;:0,&quot;mergedCount&quot;:2,&quot;declinedCount&quot;:0,&quot;total&quot;:2},&quot;open&quot;:false},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:2,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;build&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;failedBuildCount&quot;:0,&quot;successfulBuildCount&quot;:0,&quot;unknownBuildCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;review&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;stateCount&quot;:0,&quot;state&quot;:null,&quot;dueDate&quot;:null,&quot;overDue&quot;:false,&quot;completed&quot;:false},&quot;byInstanceType&quot;:{}},&quot;deployment-environment&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;topEnvironments&quot;:[],&quot;showProjects&quot;:false,&quot;successfulCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;repository&quot;:{&quot;overall&quot;:{&quot;count&quot;:3,&quot;lastUpdated&quot;:&quot;2025-04-28T19:55:11.000+0900&quot;},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:3,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;branch&quot;:{&quot;overall&quot;:{&quot;count&quot;:2,&quot;lastUpdated&quot;:null},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:2,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}}}},&quot;isStale&quot;:true}"><span class="aui-lozenge aui-lozenge-overflow aui-lozenge-subtle aui-lozenge-success fusion-widget-tooltip " title="<span class=&quot;count&quot;>2</span> pull requests">병합</span></a></span></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3152607" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3152607/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3152607_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3147849" rel="3147849" data-issuekey="WMFE-1316" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1316" href="/browse/WMFE-1316" tabindex="-1" title="WMFE-1316"></a>     <a class="issue-link" data-issue-key="WMFE-1316" href="/browse/WMFE-1316">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1316" href="/browse/WMFE-1316">WMFE-1316</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1316" href="/browse/WMFE-1316">Major[동적그룹] KR Free &gt; 그룹 리스트 및 그룹 상세 &gt; 동적 그룹 항목 노출됨</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12014" id="reporter_NT12014" href="/secure/ViewProfile.jspa?name=NT12014">이연경[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12014" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span aria-describedby="aui-tooltip"><time datetime="2025-03-25T18:59:09+0900">2025-03-25</time></span> </td><td class="updated"> <span title="2025-04-11 13:46"><time datetime="2025-04-11T13:46:32+0900">2025-04-11</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3147849" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3147849/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3147849_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3145467" rel="3145467" data-issuekey="WMFE-1289" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1289" href="/browse/WMFE-1289" tabindex="-1" title="WMFE-1289"></a>     <a class="issue-link" data-issue-key="WMFE-1289" href="/browse/WMFE-1289">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1289" href="/browse/WMFE-1289">WMFE-1289</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1289" href="/browse/WMFE-1289">[동적그룹] 그룹 부분 수정 api &gt; "dynamicMembership": null 호출 &gt; 동적그룹 -&gt; 일반그룹 변경 가능</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13263" id="assignee_NB13263" href="/secure/ViewProfile.jspa?name=NB13263">진조환[Directory Dev]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13263" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT10947" id="reporter_NT10947" href="/secure/ViewProfile.jspa?name=NT10947">임보라[QA][Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT10947" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-24 15:10"><time datetime="2025-03-24T15:10:15+0900">2025-03-24</time></span> </td><td class="updated"> <span title="2025-04-04 10:52"><time datetime="2025-04-04T10:52:19+0900">2025-04-04</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"><span class="pull-requests"><a class="fusion-widget" data-dev-type="pullrequest" data-issue-id="3145467" data-issue-key="WMFE-1289" data-dev-summary="{&quot;cachedValue&quot;:{&quot;errors&quot;:[],&quot;configErrors&quot;:[],&quot;summary&quot;:{&quot;pullrequest&quot;:{&quot;overall&quot;:{&quot;count&quot;:5,&quot;lastUpdated&quot;:&quot;2025-04-11T11:10:39.000+0900&quot;,&quot;stateCount&quot;:5,&quot;state&quot;:&quot;MERGED&quot;,&quot;details&quot;:{&quot;openCount&quot;:0,&quot;mergedCount&quot;:5,&quot;declinedCount&quot;:1,&quot;total&quot;:6},&quot;open&quot;:false},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:5,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;build&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;failedBuildCount&quot;:0,&quot;successfulBuildCount&quot;:0,&quot;unknownBuildCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;review&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;stateCount&quot;:0,&quot;state&quot;:null,&quot;dueDate&quot;:null,&quot;overDue&quot;:false,&quot;completed&quot;:false},&quot;byInstanceType&quot;:{}},&quot;deployment-environment&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;topEnvironments&quot;:[],&quot;showProjects&quot;:false,&quot;successfulCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;repository&quot;:{&quot;overall&quot;:{&quot;count&quot;:2,&quot;lastUpdated&quot;:&quot;2025-03-27T11:47:41.000+0900&quot;},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:2,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;branch&quot;:{&quot;overall&quot;:{&quot;count&quot;:6,&quot;lastUpdated&quot;:null},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:6,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}}}},&quot;isStale&quot;:true}"><span class="aui-lozenge aui-lozenge-overflow aui-lozenge-subtle aui-lozenge-success fusion-widget-tooltip " title="<span class=&quot;count&quot;>5</span> pull requests">병합</span></a></span></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3145467" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3145467/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3145467_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3145723" rel="3145723" data-issuekey="WMFE-1292" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1292" href="/browse/WMFE-1292" tabindex="-1" title="WMFE-1292"></a>     <a class="issue-link" data-issue-key="WMFE-1292" href="/browse/WMFE-1292">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1292" href="/browse/WMFE-1292">WMFE-1292</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1292" href="/browse/WMFE-1292">Major [동적그룹] Trial/Paid -&gt; 상품 해지 &gt; 기존에 생성한 동적그룹 수정 &gt; [수정]버튼 딤드 안됨 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT11572" id="reporter_NT11572" href="/secure/ViewProfile.jspa?name=NT11572">김문지[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT11572" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-24 16:55"><time datetime="2025-03-24T16:55:23+0900">2025-03-24</time></span> </td><td class="updated"> <span title="2025-04-02 17:36"><time datetime="2025-04-02T17:36:25+0900">2025-04-02</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3145723" href="/rest/api/1.0/issues/3145723/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3145723_drop" aria-haspopup="true" aria-expanded="false" aria-describedby="aui-tooltip">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3147865" rel="3147865" data-issuekey="WMFE-1315" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1315" href="/browse/WMFE-1315" tabindex="-1" title="WMFE-1315"></a>     <a class="issue-link" data-issue-key="WMFE-1315" href="/browse/WMFE-1315">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1315" href="/browse/WMFE-1315">WMFE-1315</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1315" href="/browse/WMFE-1315">Major[동적그룹] 멤버 조건 추가 레이어 &gt; 조건 개수 총합 10개 초과 생성 가능함</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12012" id="reporter_NT12012" href="/secure/ViewProfile.jspa?name=NT12012">노준일[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12012" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-25 18:22"><time datetime="2025-03-25T18:22:55+0900">2025-03-25</time></span> </td><td class="updated"> <span title="2025-04-02 14:21"><time datetime="2025-04-02T14:21:34+0900">2025-04-02</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3147865" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3147865/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3147865_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3151109" rel="3151109" data-issuekey="WMFE-1342" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1342" href="/browse/WMFE-1342" tabindex="-1" title="WMFE-1342"></a>     <a class="issue-link" data-issue-key="WMFE-1342" href="/browse/WMFE-1342">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1342" href="/browse/WMFE-1342">WMFE-1342</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1342" href="/browse/WMFE-1342">Major [동적그룹] 내부그룹 추가/수정 &gt; 멤버 [주소록] 선택 &gt; 조직도 tab에서 동적 그룹 검색 가능함</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12014" id="reporter_NT12014" href="/secure/ViewProfile.jspa?name=NT12014">이연경[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12014" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-27 17:06"><time datetime="2025-03-27T17:06:53+0900">2025-03-27</time></span> </td><td class="updated"> <span title="2025-04-02 10:11"><time datetime="2025-04-02T10:11:16+0900">2025-04-02</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3151109" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3151109/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3151109_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3151810" rel="3151810" data-issuekey="WMFE-1350" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1350" href="/browse/WMFE-1350" tabindex="-1" title="WMFE-1350"></a>     <a class="issue-link" data-issue-key="WMFE-1350" href="/browse/WMFE-1350">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1350" href="/browse/WMFE-1350">WMFE-1350</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1350" href="/browse/WMFE-1350">Major [동적그룹] 조건 '그룹' 설정 &gt; 그룹사 내 타도메인 소속 내부그룹 검색 안됨 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT11572" id="reporter_NT11572" href="/secure/ViewProfile.jspa?name=NT11572">김문지[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT11572" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-28 11:18"><time datetime="2025-03-28T11:18:20+0900">2025-03-28</time></span> </td><td class="updated"> <span title="2025-04-01 18:50"><time datetime="2025-04-01T18:50:54+0900">2025-04-01</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3151810" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3151810/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3151810_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3132820" rel="3132820" data-issuekey="WMFE-1230" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1230" href="/browse/WMFE-1230" tabindex="-1" title="WMFE-1230"></a>     <a class="issue-link" data-issue-key="WMFE-1230" href="/browse/WMFE-1230">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1230" href="/browse/WMFE-1230">WMFE-1230</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1230" href="/browse/WMFE-1230">Major [동적그룹] JP1, JP2 &gt; 동적그룹 관련 UI 노출</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT10947" id="reporter_NT10947" href="/secure/ViewProfile.jspa?name=NT10947">임보라[QA][Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT10947" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/major.svg" height="16" width="16" border="0" align="absmiddle" alt="Major" title="Major - 대부분의 기능 이상" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-17 10:25"><time datetime="2025-03-17T10:25:22+0900">2025-03-17</time></span> </td><td class="updated"> <span title="2025-03-31 15:51"><time datetime="2025-03-31T15:51:47+0900">2025-03-31</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3132820" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3132820/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3132820_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3158709" rel="3158709" data-issuekey="WMFE-1406" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1406" href="/browse/WMFE-1406" tabindex="-1" title="WMFE-1406"></a>     <a class="issue-link" data-issue-key="WMFE-1406" href="/browse/WMFE-1406">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1406" href="/browse/WMFE-1406">WMFE-1406</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1406" href="/browse/WMFE-1406">v25.5 [동적그룹] 멤버 조건 추가 &gt; 조건으로 지정된 '회사' 삭제시 에러메시지 미표시 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT11572" id="reporter_NT11572" href="/secure/ViewProfile.jspa?name=NT11572">김문지[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT11572" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>해결</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>문제에 대해 해결 방안이 제시 되었음 </span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>해결</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>문제에 대해 해결 방안이 제시 되었음 </span>" tabindex="0">해결</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-04-03 15:18"><time datetime="2025-04-03T15:18:00+0900">2025-04-03</time></span> </td><td class="updated"> <span title="2025-05-09 18:41"><time datetime="2025-05-09T18:41:45+0900">2025-05-09</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3158709" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3158709/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3158709_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3135618" rel="3135618" data-issuekey="WMFE-1262" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1262" href="/browse/WMFE-1262" tabindex="-1" title="WMFE-1262"></a>     <a class="issue-link" data-issue-key="WMFE-1262" href="/browse/WMFE-1262">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1262" href="/browse/WMFE-1262">WMFE-1262</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1262" href="/browse/WMFE-1262">v25.5 [동적그룹]&nbsp;동적 그룹 멤버 조건 추가 &gt; 예외 멤버 선택 후 저장 &gt; 예외멤버 [주소록] 재진입 시 버블 회색으로 노출됨</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12014" id="reporter_NT12014" href="/secure/ViewProfile.jspa?name=NT12014">이연경[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12014" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-18 17:14"><time datetime="2025-03-18T17:14:45+0900">2025-03-18</time></span> </td><td class="updated"> <span title="2025-05-09 17:39"><time datetime="2025-05-09T17:39:05+0900">2025-05-09</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3135618" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3135618/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3135618_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3197436" rel="3197436" data-issuekey="WMFE-1478" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1478" href="/browse/WMFE-1478" tabindex="-1" title="WMFE-1478"></a>     <a class="issue-link" data-issue-key="WMFE-1478" href="/browse/WMFE-1478">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1478" href="/browse/WMFE-1478">WMFE-1478</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1478" href="/browse/WMFE-1478">[동적그룹] 동적 그룹 데이터 복원 &gt; ‘데이터를 복원하지 못했습니다’ 얼럿 노출</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13310" id="assignee_NB13310" href="/secure/ViewProfile.jspa?name=NB13310">정재웅[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13310" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12014" id="reporter_NT12014" href="/secure/ViewProfile.jspa?name=NT12014">이연경[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12014" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-04-24 16:21"><time datetime="2025-04-24T16:21:50+0900">2025-04-24</time></span> </td><td class="updated"> <span title="2025-05-09 17:26"><time datetime="2025-05-09T17:26:06+0900">2025-05-09</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3197436" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3197436/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3197436_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3145013" rel="3145013" data-issuekey="WMFE-1287" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1287" href="/browse/WMFE-1287" tabindex="-1" title="WMFE-1287"></a>     <a class="issue-link" data-issue-key="WMFE-1287" href="/browse/WMFE-1287">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1287" href="/browse/WMFE-1287">WMFE-1287</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" aria-describedby="aui-tooltip">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1287" href="/browse/WMFE-1287">v25.5 [동적그룹] 동적그룹 멤버 수 500명 초과 &amp; 메시지 서비스 ON &gt; 동적 그룹 생성/복원 &gt; 기능 제한 안내 알럿 미노출</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12014" id="reporter_NT12014" href="/secure/ViewProfile.jspa?name=NT12014">이연경[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12014" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-24 13:39"><time datetime="2025-03-24T13:39:53+0900">2025-03-24</time></span> </td><td class="updated"> <span title="2025-05-09 17:25"><time datetime="2025-05-09T17:25:00+0900">2025-05-09</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3145013" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3145013/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3145013_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3156018" rel="3156018" data-issuekey="WMFE-1387" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1387" href="/browse/WMFE-1387" tabindex="-1" title="WMFE-1387"></a>     <a class="issue-link" data-issue-key="WMFE-1387" href="/browse/WMFE-1387">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1387" href="/browse/WMFE-1387">WMFE-1387</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1387" href="/browse/WMFE-1387">v25.5 [동적그룹] 미리보기 레이어 &gt; 오류로 멤버 불러오기 실패 시 리스트 영역 문구 변경 필요</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13310" id="assignee_NB13310" href="/secure/ViewProfile.jspa?name=NB13310">정재웅[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13310" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT10947" id="reporter_NT10947" href="/secure/ViewProfile.jspa?name=NT10947">임보라[QA][Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT10947" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-04-01 19:02"><time datetime="2025-04-01T19:02:44+0900">2025-04-01</time></span> </td><td class="updated"> <span title="2025-05-09 11:34"><time datetime="2025-05-09T11:34:18+0900">2025-05-09</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3156018" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3156018/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3156018_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3215386" rel="3215386" data-issuekey="WMFE-1548" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1548" href="/browse/WMFE-1548" tabindex="-1" title="WMFE-1548"></a>     <a class="issue-link" data-issue-key="WMFE-1548" href="/browse/WMFE-1548">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1548" href="/browse/WMFE-1548">WMFE-1548</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1548" href="/browse/WMFE-1548">[동적그룹] 동적그룹 추가 &gt; 멤버 조건 추가 완료 &gt; 수정 화면에서 간헐적으로 멤버 0명으로 보임 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13310" id="assignee_NB13310" href="/secure/ViewProfile.jspa?name=NB13310">정재웅[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13310" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT11572" id="reporter_NT11572" href="/secure/ViewProfile.jspa?name=NT11572">김문지[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT11572" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>해결</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>문제에 대해 해결 방안이 제시 되었음 </span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>해결</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>문제에 대해 해결 방안이 제시 되었음 </span>" tabindex="0">해결</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-05-08 17:05"><time datetime="2025-05-08T17:05:39+0900">2025-05-08</time></span> </td><td class="updated"> <span title="2025-05-08 18:58"><time datetime="2025-05-08T18:58:18+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3215386" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3215386/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3215386_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3215317" rel="3215317" data-issuekey="WMFE-1545" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1545" href="/browse/WMFE-1545" tabindex="-1" title="WMFE-1545"></a>     <a class="issue-link" data-issue-key="WMFE-1545" href="/browse/WMFE-1545">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="개발 sub-task" title="개발 sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1545" href="/browse/WMFE-1545">WMFE-1545</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1545" href="/browse/WMFE-1545">[동적그룹] 그룹 멤버 500명 알림 메시지 &gt; 주소록 필터 적용</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13263" id="assignee_NB13263" href="/secure/ViewProfile.jspa?name=NB13263">진조환[Directory Dev]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13263" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13313" id="reporter_NB13313" href="/secure/ViewProfile.jspa?name=NB13313">김수미[IAM/Admin Planning]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13313" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" loading="lazy" aria-describedby="aui-tooltip">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-05-08 16:24"><time datetime="2025-05-08T16:24:55+0900">2025-05-08</time></span> </td><td class="updated"> <span title="2025-05-08 17:54"><time datetime="2025-05-08T17:54:16+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"><span class="pull-requests"><a class="fusion-widget" data-dev-type="pullrequest" data-issue-id="3215317" data-issue-key="WMFE-1545" data-dev-summary="{&quot;cachedValue&quot;:{&quot;errors&quot;:[],&quot;configErrors&quot;:[],&quot;summary&quot;:{&quot;pullrequest&quot;:{&quot;overall&quot;:{&quot;count&quot;:1,&quot;lastUpdated&quot;:&quot;2025-05-10T15:22:09.000+0900&quot;,&quot;stateCount&quot;:1,&quot;state&quot;:&quot;OPEN&quot;,&quot;details&quot;:{&quot;openCount&quot;:1,&quot;mergedCount&quot;:0,&quot;declinedCount&quot;:0,&quot;total&quot;:1},&quot;open&quot;:true},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:1,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;build&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;failedBuildCount&quot;:0,&quot;successfulBuildCount&quot;:0,&quot;unknownBuildCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;review&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;stateCount&quot;:0,&quot;state&quot;:null,&quot;dueDate&quot;:null,&quot;overDue&quot;:false,&quot;completed&quot;:false},&quot;byInstanceType&quot;:{}},&quot;deployment-environment&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;topEnvironments&quot;:[],&quot;showProjects&quot;:false,&quot;successfulCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;repository&quot;:{&quot;overall&quot;:{&quot;count&quot;:2,&quot;lastUpdated&quot;:&quot;2025-05-08T17:08:09.000+0900&quot;},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:2,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;branch&quot;:{&quot;overall&quot;:{&quot;count&quot;:1,&quot;lastUpdated&quot;:null},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:1,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}}}},&quot;isStale&quot;:true}"><span class="aui-lozenge aui-lozenge-overflow aui-lozenge-subtle aui-lozenge-current fusion-widget-tooltip " title="<span class=&quot;count&quot;>1</span> pull request">검토중</span></a></span></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3215317" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3215317/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3215317_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3131568" rel="3131568" data-issuekey="WMFE-1188" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1188" href="/browse/WMFE-1188" tabindex="-1" title="WMFE-1188"></a>     <a class="issue-link" data-issue-key="WMFE-1188" href="/browse/WMFE-1188">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1188" href="/browse/WMFE-1188">WMFE-1188</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1188" href="/browse/WMFE-1188">v25.5 [동적그룹] 그룹 조건 입력 &gt; 키보드 방향키로 셀렉트박스 항목 이동 불가함 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13313" id="assignee_NB13313" href="/secure/ViewProfile.jspa?name=NB13313">김수미[IAM/Admin Planning]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13313" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT11572" id="reporter_NT11572" href="/secure/ViewProfile.jspa?name=NT11572">김문지[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT11572" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-14 11:56"><time datetime="2025-03-14T11:56:15+0900">2025-03-14</time></span> </td><td class="updated"> <span title="2025-05-08 16:33"><time datetime="2025-05-08T16:33:27+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3131568" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3131568/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3131568_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3135561" rel="3135561" data-issuekey="WMFE-1260" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1260" href="/browse/WMFE-1260" tabindex="-1" title="WMFE-1260"></a>     <a class="issue-link" data-issue-key="WMFE-1260" href="/browse/WMFE-1260">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1260" href="/browse/WMFE-1260">WMFE-1260</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1260" href="/browse/WMFE-1260">v25.5 [동적그룹] 멤버 조건 추가 레이어 &gt; 쿼리문으로 입력에서 간단입력으로 전환 &gt; 조건 그룹이 병합되거나 분리됨 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13310" id="assignee_NB13310" href="/secure/ViewProfile.jspa?name=NB13310">정재웅[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13310" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12012" id="reporter_NT12012" href="/secure/ViewProfile.jspa?name=NT12012">노준일[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12012" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-18 16:42"><time datetime="2025-03-18T16:42:29+0900">2025-03-18</time></span> </td><td class="updated"> <span title="2025-05-08 14:05"><time datetime="2025-05-08T14:05:59+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3135561" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3135561/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3135561_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3156539" rel="3156539" data-issuekey="WMFE-1390" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1390" href="/browse/WMFE-1390" tabindex="-1" title="WMFE-1390"></a>     <a class="issue-link" data-issue-key="WMFE-1390" href="/browse/WMFE-1390">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1390" href="/browse/WMFE-1390">WMFE-1390</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1390" href="/browse/WMFE-1390">v25.5 [동적그룹] 동적 그룹 멤버 추가 레이어 &gt; 편집 도중 동적그룹 상한선 도달된 상태 &gt; [확인] 선택 시 얼럿 미노출</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT10947" id="reporter_NT10947" href="/secure/ViewProfile.jspa?name=NT10947">임보라[QA][Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT10947" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-04-02 11:02"><time datetime="2025-04-02T11:02:34+0900">2025-04-02</time></span> </td><td class="updated"> <span title="2025-05-08 11:49"><time datetime="2025-05-08T11:49:30+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"><span class="pull-requests"><a class="fusion-widget" data-dev-type="pullrequest" data-issue-id="3156539" data-issue-key="WMFE-1390" data-dev-summary="{&quot;cachedValue&quot;:{&quot;errors&quot;:[],&quot;configErrors&quot;:[],&quot;summary&quot;:{&quot;pullrequest&quot;:{&quot;overall&quot;:{&quot;count&quot;:5,&quot;lastUpdated&quot;:&quot;2025-04-11T11:10:39.000+0900&quot;,&quot;stateCount&quot;:5,&quot;state&quot;:&quot;MERGED&quot;,&quot;details&quot;:{&quot;openCount&quot;:0,&quot;mergedCount&quot;:5,&quot;declinedCount&quot;:0,&quot;total&quot;:5},&quot;open&quot;:false},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:5,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;build&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;failedBuildCount&quot;:0,&quot;successfulBuildCount&quot;:0,&quot;unknownBuildCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;review&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;stateCount&quot;:0,&quot;state&quot;:null,&quot;dueDate&quot;:null,&quot;overDue&quot;:false,&quot;completed&quot;:false},&quot;byInstanceType&quot;:{}},&quot;deployment-environment&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;topEnvironments&quot;:[],&quot;showProjects&quot;:false,&quot;successfulCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;repository&quot;:{&quot;overall&quot;:{&quot;count&quot;:2,&quot;lastUpdated&quot;:&quot;2025-04-03T13:23:32.000+0900&quot;},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:2,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;branch&quot;:{&quot;overall&quot;:{&quot;count&quot;:5,&quot;lastUpdated&quot;:null},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:5,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}}}},&quot;isStale&quot;:true}"><span class="aui-lozenge aui-lozenge-overflow aui-lozenge-subtle aui-lozenge-success fusion-widget-tooltip " title="<span class=&quot;count&quot;>5</span> pull requests">병합</span></a></span></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3156539" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3156539/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3156539_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3146767" rel="3146767" data-issuekey="WMFE-1296" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1296" href="/browse/WMFE-1296" tabindex="-1" title="WMFE-1296"></a>     <a class="issue-link" data-issue-key="WMFE-1296" href="/browse/WMFE-1296">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1296" href="/browse/WMFE-1296">WMFE-1296</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1296" href="/browse/WMFE-1296">v25.5 [동적그룹] 멤버 조건 추가 레이어 &gt; 쿼리문으로 입력 + 아무 입력 없는 상태 &gt; 확인 선택 시 얼럿 노출되지 않고, 동적그룹 on 유지됨 &nbsp;</a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12012" id="reporter_NT12012" href="/secure/ViewProfile.jspa?name=NT12012">노준일[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12012" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-25 11:14"><time datetime="2025-03-25T11:14:57+0900">2025-03-25</time></span> </td><td class="updated"> <span title="2025-05-08 11:48"><time datetime="2025-05-08T11:48:38+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3146767" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3146767/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3146767_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr><tr id="issuerow3137335" rel="3137335" data-issuekey="WMFE-1274" class="issuerow"><td class="issuetype"><a class="hidden-link issue-link" data-issue-key="WMFE-1274" href="/browse/WMFE-1274" tabindex="-1" title="WMFE-1274"></a>     <a class="issue-link" data-issue-key="WMFE-1274" href="/browse/WMFE-1274">
            <img src="https://jira.navercorp.com/images/nhn/issuetype_subtask.gif" height="16" width="16" border="0" align="absmiddle" alt="QA sub-task" title="QA sub-task - " loading="lazy">
        </a>
</td><td class="issuekey">

    <a class="issue-link" data-issue-key="WMFE-1274" href="/browse/WMFE-1274">WMFE-1274</a>
</td><td class="summary"><p>
                        <a class="issue-link parentIssue" data-issue-key="WMFE-1163" href="/browse/WMFE-1163" title="[Admin] 동적 그룹 QA">WMFE-1163</a>
                        <a class="issue-link" data-issue-key="WMFE-1274" href="/browse/WMFE-1274">v25.5 [동적그룹] 조건 멤버 추가 레이어 &gt; [확인] 후 재접근 or 동적그룹 수정으로 접근 &gt; 멤버 이메일 미노출 + 임원 색상 파란색으로 표시됨 </a>
    </p>
</td><td class="assignee">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NB13305" id="assignee_NB13305" href="/secure/ViewProfile.jspa?name=NB13305">양석원[Core FE]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NB13305" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="reporter">            <span class="tinylink"><span class="jira-user-hover-wrapper"><a class="user-hover user-hover-replaced" rel="NT12012" id="reporter_NT12012" href="/secure/ViewProfile.jspa?name=NT12012">노준일[Works QA]</a><button class="aui-button aui-button-text user-hover-trigger" rel="NT12012" aria-label="사용자 정보 표시" aria-haspopup="dialog" resolved=""><span class="aui-icon aui-icon-small aui-iconfont-info-filled user-hover-trigger-icon"></span></button></span></span>
    </td><td class="priority">            <img src="https://jira.navercorp.com/images/icons/priorities/minor.svg" height="16" width="16" border="0" align="absmiddle" alt="Minor" title="Minor - 일부 기능 이상, 또는 임시 방편이 있는 경우" loading="lazy">
    </td><td class="status">
                <span class=" jira-issue-status-lozenge aui-lozenge jira-issue-status-lozenge-success jira-issue-status-lozenge-done aui-lozenge-subtle jira-issue-status-lozenge-max-width-medium" data-tooltip="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" title="<span class=&quot;jira-issue-status-tooltip-title&quot;>닫힘</span><br><span class=&quot;jira-issue-status-tooltip-desc&quot;>이슈가 처리되어 확인까지 완료한 경우</span>" tabindex="0">닫힘</span>    </td><td class="resolution">    수정
</td><td class="created"> <span title="2025-03-19 17:18"><time datetime="2025-03-19T17:18:35+0900">2025-03-19</time></span> </td><td class="updated"> <span title="2025-05-08 11:34"><time datetime="2025-05-08T11:34:33+0900">2025-05-08</time></span> </td><td class="customfield_210545"></td><td class="customfield_213734">    <div class="dev-status-column-view-wrapper"><span class="pull-requests"><a class="fusion-widget" data-dev-type="pullrequest" data-issue-id="3137335" data-issue-key="WMFE-1274" data-dev-summary="{&quot;cachedValue&quot;:{&quot;errors&quot;:[],&quot;configErrors&quot;:[],&quot;summary&quot;:{&quot;pullrequest&quot;:{&quot;overall&quot;:{&quot;count&quot;:1,&quot;lastUpdated&quot;:&quot;2025-04-28T16:29:48.000+0900&quot;,&quot;stateCount&quot;:1,&quot;state&quot;:&quot;MERGED&quot;,&quot;details&quot;:{&quot;openCount&quot;:0,&quot;mergedCount&quot;:1,&quot;declinedCount&quot;:0,&quot;total&quot;:1},&quot;open&quot;:false},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:1,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;build&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;failedBuildCount&quot;:0,&quot;successfulBuildCount&quot;:0,&quot;unknownBuildCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;review&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;stateCount&quot;:0,&quot;state&quot;:null,&quot;dueDate&quot;:null,&quot;overDue&quot;:false,&quot;completed&quot;:false},&quot;byInstanceType&quot;:{}},&quot;deployment-environment&quot;:{&quot;overall&quot;:{&quot;count&quot;:0,&quot;lastUpdated&quot;:null,&quot;topEnvironments&quot;:[],&quot;showProjects&quot;:false,&quot;successfulCount&quot;:0},&quot;byInstanceType&quot;:{}},&quot;repository&quot;:{&quot;overall&quot;:{&quot;count&quot;:1,&quot;lastUpdated&quot;:&quot;2025-04-28T13:15:17.000+0900&quot;},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:1,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}},&quot;branch&quot;:{&quot;overall&quot;:{&quot;count&quot;:1,&quot;lastUpdated&quot;:null},&quot;byInstanceType&quot;:{&quot;githube&quot;:{&quot;count&quot;:1,&quot;name&quot;:&quot;GitHub Enterprise&quot;}}}}},&quot;isStale&quot;:true}"><span class="aui-lozenge aui-lozenge-overflow aui-lozenge-subtle aui-lozenge-success fusion-widget-tooltip " title="<span class=&quot;count&quot;>1</span> pull request">병합</span></a></span></div>
</td><td class="issue_actions">    <a class="issue-actions-trigger aui-button aui-button-compact aui-button-subtle trigger-happy" id="actions_3137335" title="조치 (이슈 조치를 보기 위해 . 을 입력하세요)" href="/rest/api/1.0/issues/3137335/ActionsAndOperations?atl_token=AXYA-2K30-4QQF-89AQ_1d617f19682782e23509b8937c47d850da9b69fe_lin" resolved="" aria-controls="actions_3137335_drop" aria-haspopup="true" aria-expanded="false">
        <span class="aui-icon aui-icon-small aui-iconfont-more">조치</span>
    </a>
</td></tr></tbody>

"""